# Generated by Django 5.1.5 on 2025-09-26 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_contactmessage_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='submitted_at',
        ),
    ]
