# Generated by Django 5.1.5 on 2025-09-26 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_created_at_contact_submitted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='submitted_at',
            new_name='created_at',
        ),
    ]
